apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: solar
      defaultBucket: solar
    secureJsonData:
      token: kostal-solar-token
    isDefault: true
    editable: true
